# Generated by Django 5.2.9 on 2025-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='客戶姓名')),
                ('policy_id', models.CharField(max_length=50, unique=True, verbose_name='保單編號')),
                ('policy_type', models.CharField(max_length=100, verbose_name='保險種類')),
                ('coverage_amount', models.IntegerField(verbose_name='保險金額')),
                ('start_date', models.DateField(verbose_name='投保日期')),
                ('expiry_date', models.DateField(verbose_name='到期日期')),
                ('premium', models.IntegerField(verbose_name='保費')),
                ('status', models.CharField(default='有效', max_length=20, verbose_name='狀態')),
            ],
        ),
    ]
